PUT http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer 

{
    "title": "A second blog submitted by user two",
    "author": "author",
    "url": "url",
    "likes": 5
}